# Generated by Django 5.2.1 on 2025-06-11 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_rename_user_post_author_post_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='user',
        ),
    ]
